[build]
  # The command Netlify will run to build your project
  command = "npm run build"
  
  # The directory where the built files are located
  publish = "build/client"

  # Specify the Node.js version to match your package.json engines
  environment = { 
    NODE_VERSION = "18.18.0" 
  }

# Optional: Define environment variables if needed
# [build.environment]
#   YOUR_ENV_VAR = "your_value"

# Optional: Redirects and rewrites for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Configure functions if your app uses Netlify Functions
# [functions]
#   directory = "netlify/functions"

# Optional: Specify plugins if you are using any Netlify plugins
# [[plugins]]
#   package = "netlify-plugin-your-plugin"
