[build]
  command = "npm run build"
  publish = "public" # This should match the output directory defined by the Remix Netlify adapter
  functions = "netlify/functions" # Directory for Netlify Functions

# Redirect all requests to the Remix serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true

# Optional: Specify environment variables (if any)
#[build.environment]
#  NODE_ENV = "production"
#  OTHER_ENV_VAR = "value"

# Optional: Define Edge Handlers or other advanced configurations
#[edge_handlers]
#  path = "/some-path"
#  handler = "path/to/handler.js"
